FROM ubuntu:latest

WORKDIR /root/

RUN apt-get update &&\
    apt-get install -y wget iproute2 openssh-server systemctl &&\
    echo \
    'service ssh start\
     wget -O nezha.sh https://raw.githubusercontents.com/naiba/nezha/master/script/install.sh && chmod +x nezha.sh && ./nezha.sh install_agent $NEZHA_SERVER $NEZHA_PORT $NEZHA_KEY\
     tail -f /dev/null' | sed 's/   */\n/g' > "start.sh" &&\
    chmod +x start.sh

ENTRYPOINT ./start.sh
